// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAbBDzbNUrbyK9f_vcYOeA_yG1vSxBuHg',
    appId: '1:240403571417:web:9cc4dfa5402fafcdae54c8',
    messagingSenderId: '240403571417',
    projectId: 'fyp-project-6a908',
    authDomain: 'fyp-project-6a908.firebaseapp.com',
    storageBucket: 'fyp-project-6a908.appspot.com',
    measurementId: 'G-XPPC94YJJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPjaSfM3f6PO-9wWJRXpT2o8g8FaREbTs',
    appId: '1:240403571417:android:052ea9ddb0b77149ae54c8',
    messagingSenderId: '240403571417',
    projectId: 'fyp-project-6a908',
    storageBucket: 'fyp-project-6a908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcKQroIBhDyo8mHlrlvQv034Cmqhjf0Aw',
    appId: '1:240403571417:ios:90c91aa5d76779e6ae54c8',
    messagingSenderId: '240403571417',
    projectId: 'fyp-project-6a908',
    storageBucket: 'fyp-project-6a908.appspot.com',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcKQroIBhDyo8mHlrlvQv034Cmqhjf0Aw',
    appId: '1:240403571417:ios:90c91aa5d76779e6ae54c8',
    messagingSenderId: '240403571417',
    projectId: 'fyp-project-6a908',
    storageBucket: 'fyp-project-6a908.appspot.com',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAbBDzbNUrbyK9f_vcYOeA_yG1vSxBuHg',
    appId: '1:240403571417:web:75392d99d9fe97a5ae54c8',
    messagingSenderId: '240403571417',
    projectId: 'fyp-project-6a908',
    authDomain: 'fyp-project-6a908.firebaseapp.com',
    storageBucket: 'fyp-project-6a908.appspot.com',
    measurementId: 'G-YC9RZZL905',
  );
}
